//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncodingConverter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class EncodingConverterConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static EncodingConverterConfig defaultInstance = ((EncodingConverterConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EncodingConverterConfig())));
        
        public static EncodingConverterConfig Default {
            get {
                return defaultInstance;
            }
        }
    }
}
